# Generated by Django 3.0.4 on 2020-03-23 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lexeme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lexema', models.TextField()),
                ('part_of_speech', models.TextField()),
                ('gram', models.TextField()),
                ('synopsis', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='LexemeDescr',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('stylistic', models.TextField()),
                ('examples', models.TextField()),
                ('definition', models.TextField()),
                ('comment_to_def', models.TextField()),
                ('subcategorization', models.TextField()),
                ('comment_to_subc', models.TextField()),
                ('constr', models.TextField()),
                ('comp', models.TextField()),
                ('illustrations', models.TextField()),
                ('lexical', models.TextField()),
                ('phraseology', models.TextField()),
                ('lexema_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='slovnik.Lexeme')),
            ],
        ),
    ]
